export const HELPER_PATH = '/usr/local/lib/metro/root-helper';
export const HELPER_VERSION = 1;
export const SUDOERS_PATH = '/etc/sudoers.d/metro';
export const METRO_USER = 'metro';
export const METRO_HOME = '/var/lib/metro';

export const sudoersText = (agent: string): string =>
  [
    `${METRO_USER} ALL=(${agent}) NOPASSWD: ALL`,
    `${METRO_USER} ALL=(root) NOPASSWD: ${HELPER_PATH} *`,
    `Defaults:${METRO_USER} !requiretty`,
    '',
  ].join('\n');

const lines = (...parts: string[]): string => parts.join('\n');

const CHECKS = lines(
  'AGENT=agent',
  'UNITS=/etc/systemd/system',
  'die() { echo "root-helper: $*" >&2; exit 2; }',
  'agent_uid() { id -u "$AGENT" 2>/dev/null || die "no agent user"; }',
  'service_ok() {',
  '  printf %s "$1" | grep -Eq "^[A-Za-z0-9@_.-]+\\.service$" || die "bad service name"',
  '  case "$1" in metro*) die "not a metro unit";; esac',
  '  frag=$(systemctl show "$1" -p FragmentPath --value)',
  '  case "$frag" in "$UNITS"/*) ;; *) die "not a unit under $UNITS";; esac',
  '  systemctl show "$1" -p TriggeredBy --value | grep -q "\\.timer" || die "not started by a timer"',
  '}',
  'dropin_ok() {',
  '  case "$1" in 10-metro-agent.conf|11-metro-vault.conf) ;; *) die "bad drop-in name";; esac',
  '  home=$(getent passwd "$AGENT" | cut -d: -f6)',
  '  saw_user=0',
  '  while IFS= read -r line; do',
  '    case "$line" in',
  '      "[Service]"|"") ;;',
  '      "User=$AGENT") saw_user=1 ;;',
  '      Group=*) printf %s "${line#Group=}" | grep -Eq "^[0-9]+$" || die "bad group" ;;',
  '      "WorkingDirectory=$home"|"WorkingDirectory=$home"/*) ;;',
  '      Environment=*) ;;',
  '      "EnvironmentFile=-$home/.metro/vault.env") ;;',
  '      "ExecStart=") ;;',
  '      ExecStart=[+!@]*) die "privileged ExecStart refused" ;;',
  '      ExecStart=*) ;;',
  '      *) die "line not allowed: $line" ;;',
  '    esac',
  '  done < "$2"',
  '  if [ "$1" = 10-metro-agent.conf ] && [ "$saw_user" != 1 ]; then die "the drop-in must set User=$AGENT"; fi',
  '}',
);

const FIREWALL = lines(
  'firewall_on() {',
  '  uid=$(agent_uid)',
  '  for t in iptables ip6tables; do',
  '    $t -w -N METRO_AGENT 2>/dev/null || true',
  '    $t -w -F METRO_AGENT',
  '    $t -w -A METRO_AGENT -o lo -j ACCEPT',
  '    $t -w -A METRO_AGENT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT',
  '    $t -w -A METRO_AGENT -p udp --dport 53 -j ACCEPT',
  '    $t -w -A METRO_AGENT -p tcp --dport 53 -j ACCEPT',
  '    $t -w -A METRO_AGENT -p tcp -j REJECT --reject-with tcp-reset',
  '    $t -w -A METRO_AGENT -j REJECT',
  '    $t -w -C OUTPUT -m owner --uid-owner "$uid" -j METRO_AGENT 2>/dev/null || $t -w -I OUTPUT -m owner --uid-owner "$uid" -j METRO_AGENT',
  '  done',
  '}',
  'firewall_off() {',
  '  uid=$(agent_uid)',
  '  for t in iptables ip6tables; do',
  '    while $t -w -C OUTPUT -m owner --uid-owner "$uid" -j METRO_AGENT 2>/dev/null; do $t -w -D OUTPUT -m owner --uid-owner "$uid" -j METRO_AGENT; done',
  '    $t -w -F METRO_AGENT 2>/dev/null || true',
  '    $t -w -X METRO_AGENT 2>/dev/null || true',
  '  done',
  '}',
);

const ACTIONS = lines(
  'action="${1:-}"; [ "$#" -gt 0 ] && shift',
  'case "$action" in',
  `  version) echo ${String(HELPER_VERSION)} ;;`,
  '  ensure-agent)',
  '    getent passwd "$AGENT" >/dev/null || useradd --create-home --shell /bin/bash "$AGENT"',
  '    chmod 700 "$(getent passwd "$AGENT" | cut -d: -f6)" ;;',
  '  as-agent-scope)',
  '    [ "$#" -ge 3 ] || die "usage: as-agent-scope <max> <high> <command...>"',
  '    printf %s "$1$2" | grep -Eq "^[0-9]+$" || die "bad memory limits"',
  '    max="$1"; high="$2"; shift 2',
  '    uid=$(agent_uid); gid=$(id -g "$AGENT")',
  '    exec systemd-run --scope --quiet --collect --unit="metro-claude-$(date +%s%N)" -p MemoryMax="$max" -p MemoryHigh="$high" -p OOMPolicy=continue -- setpriv --reuid="$uid" --regid="$gid" --init-groups -- "$@" ;;',
  '  dropin-write)',
  '    service_ok "$1"; tmp=$(mktemp); trap \'rm -f "$tmp"\' EXIT; cat > "$tmp"; dropin_ok "$2" "$tmp"',
  '    mkdir -p "$UNITS/$1.d"; install -m 644 "$tmp" "$UNITS/$1.d/$2" ;;',
  '  dropin-remove)',
  '    service_ok "$1"; case "$2" in 10-metro-agent.conf|11-metro-vault.conf) ;; *) die "bad drop-in name";; esac',
  '    rm -f "$UNITS/$1.d/$2" ;;',
  '  daemon-reload) systemctl daemon-reload ;;',
  '  start-job)',
  '    service_ok "$1"; [ "$(systemctl show "$1" -p User --value)" = "$AGENT" ] || die "that job does not run as $AGENT"',
  '    systemctl start --no-block "$1" ;;',
  '  root-crontab) crontab -l -u root 2>/dev/null || true ;;',
  '  root-crontab-drop)',
  '    printf %s "$1" | grep -Eq "^[0-9a-f]{16}$" || die "bad line id"',
  `    backups="${METRO_HOME}/.metro/agents"`,
  '    cur=$(mktemp); crontab -l -u root > "$cur" 2>/dev/null || true',
  '    kept=$(mktemp); found=0',
  '    while IFS= read -r line; do',
  '      id=$(printf %s "$line" | sed "s/^[[:space:]]*//;s/[[:space:]]*$//" | tr -d "\\n" | sha256sum | cut -c1-16)',
  '      if [ "$id" = "$1" ] && [ "$found" = 0 ]; then found=1; elif [ -n "$line" ]; then printf "%s\\n" "$line" >> "$kept"; fi',
  '    done < "$cur"',
  '    [ "$found" = 1 ] || die "that cron line is gone"',
  '    install -m 600 "$cur" "$backups/crontab-root.$(date +%Y-%m-%dT%H-%M-%S).bak"',
  '    crontab -u root "$kept"; rm -f "$cur" "$kept" ;;',
  '  firewall-on) firewall_on ;;',
  '  firewall-off) firewall_off ;;',
  '  trust-ca)',
  `    src="${METRO_HOME}/.metro/agents/vault/ca/ca.crt"`,
  '    head -n1 "$src" | grep -q "BEGIN CERTIFICATE" || die "not a certificate"',
  '    if grep -q "PRIVATE KEY" "$src"; then die "a key is not a certificate"; fi',
  '    install -m 644 "$src" /usr/local/share/ca-certificates/metro-vault.crt && update-ca-certificates >/dev/null ;;',
  '  untrust-ca) rm -f /usr/local/share/ca-certificates/metro-vault.crt; update-ca-certificates --fresh >/dev/null ;;',
  '  install-nss-tools) DEBIAN_FRONTEND=noninteractive apt-get install -y -q libnss3-tools >/dev/null ;;',
  '  *) die "unknown action: $action" ;;',
  'esac',
);

export const helperScript = (): string =>
  ['#!/bin/sh', 'set -eu', 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', CHECKS, FIREWALL, ACTIONS, ''].join('\n');
