import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { hearSharedCall } from '../../apps/daemon/src/voice/shared.js';
import * as h from './shared-call-harness.js';

export async function resumedCompaction(): Promise<void> {
  const session = h.agent.runner.id;
  const warm = await h.call();
  h.upstream.inputTokens = 130_000;
  h.chat('FIXTURE_CHAT_HIGH_CONTEXT');
  await h.until('high context chat', () => h.sent('FIXTURE_CHAT_HIGH_CONTEXT') === 1);
  await h.idle();
  warm.end();
  await h.idle();
  const saved: { context: number } = JSON.parse(readFileSync(join(h.ROOT, 'session.json'), 'utf8'));
  assert.ok(saved.context >= 130_000);
  await h.agent.stop();
  await h.agent.done;
  h.upstream.inputTokens = 50;
  h.upstream.holdCompaction = true;
  const eventStart = h.events.length;
  await h.boot(120_000, false);
  await h.until('resumed high context compaction', () => h.upstream.held.has('compaction') && h.activity.snapshot().mainPhase === 'compacting');
  const compactInput = h.activity.snapshot().inputs?.find((input) => input.kind === 'note');
  assert.ok(compactInput);
  const fake = await h.call('fixture-during-compaction', false);
  hearSharedCall(fake.route, 'FIXTURE_VOICE answer after this compaction.', 'voice-after-compaction');
  h.chat('FIXTURE_CHAT_DURING_COMPACTION');
  await h.until('compaction queues chat and voice', () => h.activity.snapshot().pending >= 2);
  const requests = h.upstream.seen.length;
  const started = Date.now();
  await Bun.sleep(21_000);
  assert.equal(h.upstream.seen.length, requests);
  assert.equal(h.activity.snapshot().mainPhase, 'compacting');
  assert.equal(h.sent('FIXTURE_CHAT_DURING_COMPACTION'), 0);
  assert.deepEqual(fake.synthesized, []);
  h.upstream.holdCompaction = false;
  h.upstream.release('compaction');
  await h.until('chat and voice after compaction', () => h.sent('FIXTURE_CHAT_DURING_COMPACTION') === 1 && fake.frames.length === 1);
  await h.idle();
  assert.equal(h.agent.runner.id, session);
  assert.ok(h.events.some((event) => event.type === 'system' && event.subtype === 'compact_boundary'));
  assert.deepEqual(fake.synthesized, ['Voice fixture answer.']);
  fake.end();
  await h.idle();
  const lifecycle = h.events.slice(eventStart).filter((event) => event.type === 'command_lifecycle' || event.type === 'result' || event.subtype === 'compact_boundary').map((event) => ({ type: event.type, subtype: event.subtype, state: event.state, command: event.command_uuid, consumed: event.user_message_uuids }));
  const exactResultUuid = h.events.slice(eventStart).some((event) => event.type === 'result' && Array.isArray(event.user_message_uuids) && event.user_message_uuids.includes(compactInput.id));
  h.report('high context resume and slow compaction', { savedContext: saved.context, heldMs: Date.now() - started, chatAndVoiceQueued: true, noCompactionInterrupt: true, nextChatAnswered: true, sameSession: true, compactInput: h.activity.snapshot().inputs?.find((input) => input.id === compactInput.id), exactResultUuid, lifecycle });
  assert.equal(exactResultUuid, true);
  assert.equal(h.activity.snapshot().inputs?.find((input) => input.id === compactInput.id)?.state, 'completed');
  const boundaries = h.events.filter((event) => event.subtype === 'compact_boundary').length;
  h.upstream.inputTokens = 130_000;
  h.upstream.holdCompaction = true;
  h.chat('FIXTURE_CHAT_HIGH_CONTEXT_AGAIN');
  await h.until('second high context chat', () => h.sent('FIXTURE_CHAT_HIGH_CONTEXT_AGAIN') === 1);
  await h.until('second automatic compaction rearms', () => h.upstream.held.has('compaction') && h.activity.snapshot().mainPhase === 'compacting');
  h.upstream.inputTokens = 50;
  h.upstream.holdCompaction = false;
  h.upstream.release('compaction');
  await h.until('second compact boundary', () => h.events.filter((event) => event.subtype === 'compact_boundary').length === boundaries + 1);
  await h.idle();
  h.chat('FIXTURE_CHAT_AFTER_SECOND_COMPACTION');
  await h.until('chat after second compaction', () => h.sent('FIXTURE_CHAT_AFTER_SECOND_COMPACTION') === 1);
  await h.idle();
  assert.equal(h.agent.runner.id, session);
  h.report('repeated compaction rearmed', { secondCompactionCompleted: true, nextChatAnswered: true, sameSession: true });
}
