// Discord station verb declarations (data only). Mirror the dispatch chain in
// stations/discord/actions.ts.

import { v } from '../../schema.js';
import { line, type VerbDecl } from '../../registry-types.js';

const acct = v.optional(v.string());

export const DISCORD_VERBS: VerbDecl[] = [
  { name: 'accounts', owner: 'discord', kind: 'read', idempotent: true,
    description: 'List booted Discord accounts (id, userId, username, ready).',
    example: 'metro call discord accounts' },
  { name: 'send', owner: 'discord', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, text: v.optional(v.string()), account: acct }),
    description: 'Send a message to a channel.',
    example: 'metro send metro://discord/<chan> "hello"' },
  { name: 'reply', owner: 'discord', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, messageId: v.string(), text: v.string(), account: acct }),
    description: 'Reply to a message.',
    example: 'metro reply metro://discord/<chan> <msgId> "thanks"' },
  { name: 'react', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), emoji: v.optional(v.string()), account: acct }),
    description: 'Add (emoji) or remove (no emoji) a reaction.',
    example: 'metro react metro://discord/<chan> <msgId> 👍' },
  { name: 'edit', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), text: v.string(), account: acct }),
    description: 'Edit a previously-sent message.',
    example: 'metro edit metro://discord/<chan> <msgId> "fixed"' },
  { name: 'delete', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), account: acct }),
    description: 'Delete a message.',
    example: 'metro delete metro://discord/<chan> <msgId>' },
  { name: 'fetch', owner: 'discord', kind: 'read', idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Fetch recent messages from a channel.',
    example: 'metro call discord fetch \'{"line":"…","limit":20}\'' },
  { name: 'download', owner: 'discord', kind: 'read', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), account: acct }),
    description: 'Download a message\'s attachments to disk.',
    example: 'metro call discord download \'{"line":"…","messageId":"…"}\'' },
  { name: 'thread_create', owner: 'discord', kind: 'mutate', idempotent: false,
    inputSchema: v.object({ line, name: v.string(), account: acct }),
    description: 'Create a thread (from a message or standalone).',
    example: 'metro call discord thread_create \'{"line":"…","name":"…"}\'' },
  { name: 'pin', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), account: acct }),
    description: 'Pin a message in a channel.',
    example: 'metro call discord pin \'{"line":"…","messageId":"…"}\'' },
  { name: 'typing', owner: 'discord', kind: 'mutate', idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a typing indicator to a channel.',
    example: 'metro call discord typing \'{"line":"…"}\'' },
  { name: 'channel', owner: 'discord', kind: 'read', idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Read channel metadata.',
    example: 'metro call discord channel \'{"line":"…"}\'' },
  { name: 'set_presence', owner: 'discord', kind: 'mutate', idempotent: true,
    description: 'Set the bot presence / custom status.',
    example: 'metro call discord set_presence \'{"status":"online"}\'' },
  { name: 'joinVoice', owner: 'discord', kind: 'mutate', idempotent: true,
    description: 'Join a voice channel.',
    example: 'metro call discord joinVoice \'{"line":"…"}\'' },
  { name: 'leaveVoice', owner: 'discord', kind: 'mutate', idempotent: true,
    description: 'Leave the current voice channel.',
    example: 'metro call discord leaveVoice \'{"line":"…"}\'' },
  { name: 'speak', owner: 'discord', kind: 'mutate', idempotent: false,
    description: 'Speak text (TTS) in a voice channel.',
    example: 'metro call discord speak \'{"line":"…","text":"…"}\'' },
  { name: 'voiceDebug', owner: 'discord', kind: 'read', idempotent: true,
    description: 'Dump voice-connection debug state.',
    example: 'metro call discord voiceDebug \'{"line":"…"}\'' },
  { name: 'voiceTranscribe', owner: 'discord', kind: 'mutate', idempotent: false,
    description: 'Transcribe captured voice audio.',
    example: 'metro call discord voiceTranscribe \'{"line":"…"}\'' },
];
