import { v } from '../../schema.js';
import { line, type VerbDecl } from '../../registry-types.js';

const acct = v.optional(v.string());

export const TELEGRAM_VERBS: VerbDecl[] = [
  {
    name: 'accounts',
    owner: 'telegram',
    kind: 'read',
    idempotent: true,
    description: 'List booted Telegram accounts.',
    example: 'metro call telegram accounts',
  },
  {
    name: 'send',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: false,
    inputSchema: v.object({
      line,
      text: v.optional(v.string()),
      account: acct,
    }),
    description: 'Send a text message to a chat.',
    example: 'metro send metro://telegram/<chat> "hello"',
  },
  {
    name: 'react',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: true,
    inputSchema: v.object({
      line,
      messageId: v.string(),
      emoji: v.optional(v.string()),
      account: acct,
    }),
    description: 'Set (emoji) or clear (no emoji) a reaction on a message.',
    example: 'metro react metro://telegram/<chat> <msgId> 👍',
  },
  {
    name: 'edit',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: true,
    inputSchema: v.object({
      line,
      messageId: v.string(),
      text: v.string(),
      account: acct,
    }),
    description: 'Edit a previously-sent message.',
    example: 'metro edit metro://telegram/<chat> <msgId> "fixed"',
  },
  {
    name: 'delete',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: true,
    inputSchema: v.object({ line, messageId: v.string(), account: acct }),
    description: 'Delete a message.',
    example: 'metro delete metro://telegram/<chat> <msgId>',
  },
  {
    name: 'send_photo',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a photo to a chat.',
    example: 'metro call telegram send_photo \'{"line":"…","path":"…"}\'',
  },
  {
    name: 'send_document',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a document/file to a chat.',
    example: 'metro call telegram send_document \'{"line":"…","path":"…"}\'',
  },
  {
    name: 'send_voice',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a voice note to a chat.',
    example: 'metro call telegram send_voice \'{"line":"…","path":"…"}\'',
  },
  {
    name: 'send_sticker',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a sticker to a chat.',
    example: 'metro call telegram send_sticker \'{"line":"…","sticker":"…"}\'',
  },
  {
    name: 'send_dice',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send an animated dice/emoji game to a chat.',
    example: 'metro call telegram send_dice \'{"line":"…"}\'',
  },
  {
    name: 'send_location',
    owner: 'telegram',
    kind: 'mutate',
    idempotent: false,
    inputSchema: v.object({ line, account: acct }),
    description: 'Send a location to a chat.',
    example:
      'metro call telegram send_location \'{"line":"…","lat":0,"lon":0}\'',
  },
  {
    name: 'read',
    owner: 'telegram',
    kind: 'read',
    idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: 'Read recent messages from a chat.',
    example: 'metro call telegram read \'{"line":"…"}\'',
  },
  {
    name: 'download',
    owner: 'telegram',
    kind: 'read',
    idempotent: true,
    inputSchema: v.object({ line, account: acct }),
    description: "Download a message's media to disk.",
    example: 'metro call telegram download \'{"line":"…","messageId":"…"}\'',
  },
];
